### ISSUE TITLE
apx install --sideload does not work

### ISSUE THREAD

**Issue by alihassan1989** [Vanilla-OS/iso-builder#54] opened 2022-12-31 19:19 UTC
i have installed docker and all of its dependencies in the transactional shell and after reboot i tested docker in the terminal and everything worked fine. I need the docker gui but I can't get it to install. I even downloaded the .deb package and ran apx install --sideload  path/to/package.deb (I used the actual location and package name) but I keep getting an error. I tried another .deb package but still received an error.

 **here are some screenshots of the errors:**
https://github.com/alihassan1989/vanillaOS-screenshots/blob/main/Screenshot%20from%202022-12-31%2011-44-50.png
https://github.com/alihassan1989/vanillaOS-screenshots/blob/main/Screenshot%20from%202022-12-31%2012-07-55.png

**Comment by mks-h** [comment] 2023-01-01 16:49
Have you tried going `abroot shell` and install it there like you would on a regular Ubuntu?

**Comment by alihassan1989** [comment] 2023-01-02 02:54
yes I did, it gave me the same error. every time I try to install a .deb file it fails and it moves the .deb file to /home/user/.cache/apx/

**Comment by lukeco11** [comment] 2023-01-03 21:38
I have this same problem when installing a .deb. Apx throws that error at the end, and the app is nowhere to be found.

**Comment by sbe-arg** [comment] 2023-01-07 00:35
what are you actually triying installing? docker desktop on top of docker engine? 

I'm using docker on installed via abroot and use portainer.io if I need any form of UI
I did tried installing docker-desktop via abroot and worked without docker-engine installed docker-engine is included in the installer if you are using different types of docker bits installs apx and not abroot you will get weird errors.
![image](https://user-images.githubusercontent.com/23391642/211122106-140bf55f-b3cc-4566-af20-088754b878ff.png)

install it via repository in abroot and not via .deb https://docs.docker.com/engine/install/ubuntu/#set-up-the-repository

**Comment by kbdharun** [comment] 2023-01-07 01:39
There is a whole Discussion on installing Docker in server https://discord.com/channels/1023243680829681704/1059739495618072657

Which will be useful here.

**Comment by mirkobrombin** [comment] 2023-02-05 20:48
Closing since the sideload works and the problem is related to the package. Also the correct repository was Apx.

**Closed as completed by mirkobrombin** 2023-02-05 20:48 UTC
