### ISSUE TITLE
Plans for Xfce spin

### ISSUE THREAD

**Issue by Klibrugak** [Vanilla-OS/iso-builder#142] opened 2023-02-20 01:17 UTC
Are there future plans to release an xfce variant of Vanilla Os? 
I managed to install it trough abroot  but I haven't removed the Gnome environment out of fear of breaking something important.
I would be nice to have a Vanilla Xfce desktop with the versatility of vanilla Os.

(Sorry if this isn't the right medium to ask this question)

**Comment by mirkobrombin** [comment] 2023-02-20 07:57
Duplicate of: #120 

--

PS. yes, removing gnome will remove core vanilla apps as well.

**Closed as completed by mirkobrombin** 2023-02-20 07:57 UTC
