### ISSUE TITLE
quotation mark is weird in translation

### ISSUE THREAD

**Issue by mttbx** [Vanilla-OS/iso-builder#260] opened 2023-11-05 01:50 UTC
### Issue Description

![截图 2023-11-05 09-49-46](https://github.com/Vanilla-OS/live-iso/assets/38148377/5afb5e53-60fa-4eba-9d1b-5b7c6af5e1f9)

### Steps to Reproduce

flatpak install neovim

### On what version of Vanilla OS this happens?

Unreleased

**Comment by me-self** [comment] 2023-11-07 01:53
Do you have a custom font?

**Comment by mttbx** [comment] 2023-11-07 07:50
I use the Monospace 24. The default font is small.
But If I use the default system font, the issue is the same.

**Comment by me-self** [comment] 2023-11-11 14:39
What piece of software is displaying this text?

**Comment by axtloss** [comment] 2023-11-11 14:45
What language/locale is your system set to? Did you select any extra language during installation that is not English

**Comment by me-self** [comment] 2023-11-11 14:50
Mine is set to English (GB) I might be able to test another in the installer.

**Comment by axtloss** [comment] 2023-11-11 14:54
The question was directed to mttbx, since the different quotation marks are most likely a result of a different locale being used.

**Comment by me-self** [comment] 2023-11-12 07:14
> The question was directed to mttbx, since the different quotation marks are most likely a result of a different locale being used.

Oh oops, I though you were mttbx :sweat_smile:

**Comment by mttbx** [comment] 2023-11-13 01:27
The locale is CN. I set chinese during installation. And I got the weird mark when I used flatpak to install some packages.

**Comment by axtloss** [comment] 2023-11-14 22:25
Try changing the local to en_US, the issue is most likely related to you using a chinese locale which makes flatpak use these quotation marks

**Comment by mttbx** [comment] 2023-11-15 01:10
I think this is because the quotation graphic size is not correct. In C, this can be fixed by using some reversioned wcwidth.

**Comment by mirkobrombin** [comment] 2024-01-30 07:25
Closing this issue as it pertains to the alpha version, and we are transitioning to the beta release. If the issue still exists or is relevant in the beta version, please feel free to reopen with updated information.

Thank you for your contribution and understanding.

**Closed as completed by mirkobrombin** 2024-01-30 07:25 UTC
Labels: bug, triage
