### ISSUE TITLE
 error creating container: exit status 125

### ISSUE THREAD

**Issue by TheCorruptCat** [Vanilla-OS/iso-builder#123] opened 2023-02-01 13:37 UTC
### Issue Description

when i try to use apx it says  error creating container: exit status 125

### Steps to Reproduce

open console try apx install then you get that error

### On what version of Vanilla OS this happens?

22.10

**Comment by kbdharun** [comment] 2023-02-01 13:40
Duplicate of https://github.com/Vanilla-OS/apx/issues/97
This issue is being actively investigated in #dev.

**Closed as completed** 2023-02-01 14:04 UTC
Labels: bug, triage
