### ISSUE TITLE
Skipping mandatory steps in the Vanilla OS Installer

### ISSUE THREAD

**Issue by BassBoy320** [Vanilla-OS/iso-builder#196] opened 2023-06-03 14:18 UTC
### Issue Description

When arriving at step "Select a disk" the user is able to skip it by pressing the Enter key or the Space bar.
This is also the case for the following steps, e.g. "Create User" and "Install Vanilla OS".
The installer then obviously never finishes and keeps displaying "Installing..."

### Steps to Reproduce

- Start the VanillaOS-22.10-all.20230226.iso in a virtual machine (but I am sure this happens on bare metal too)
- Open the Vanilla OS Installer
- Choose "Install Vanilla OS"
- Click on the next button at the right side until step "Select a disk"
- Press the Enter key or the Space bar

### On what version of Vanilla OS this happens?

22.10

### Additional Information

I assume this happens, because the arrow button for the next step is still in focus while being invisible.

**Comment by mirkobrombin** [comment] 2023-06-03 16:43
Possible duplicate, related:
- https://github.com/Vanilla-OS/vanilla-installer/issues/65
- https://github.com/Vanilla-OS/vanilla-installer/issues/62

**Comment by mirkobrombin** [comment] 2023-06-03 16:44
Actually duplicate of https://github.com/Vanilla-OS/vanilla-installer/issues/65

**Closed as completed by mirkobrombin** 2023-06-03 16:44 UTC
Labels: bug, triage
