### ISSUE TITLE
Gnome software shows "updates available" all the time, doesnt change

### ISSUE THREAD

**Issue by secretmango** [Vanilla-OS/iso-builder#182] opened 2023-04-18 15:47 UTC
### Issue Description

I installed VanillaOS-22.10-all.20230226 in virt-manager

I go to Software and see updates, I click "reboot now" and it reboots. The message stays there though, I tried rebooting 3 times.

I have no idea of A/B partitions, I installed it using automatic partitioning.

I disabled the smart update too, as my VM may mess with it (this is a bug then! VMs normally report AC afaik)

### Steps to Reproduce

- install VanillaOS
- go to Software and try to update, reboot
- go to Software again

### On what version of Vanilla OS this happens?

22.10

**Comment by kbdharun** [comment] 2023-04-18 17:56
Is the package showing an update every time related to Ubuntu pro? 

We have prior reports in our Discord server with a similar issue where even after restart an update is shown (not just in gnome software, vso and even the now removed updates popup in Vanilla control center).

If this is an Ubuntu specific issue, it should be fixed with the Debian base migration.

**Comment by boredsquirrel** [comment] 2023-04-20 15:20
No for example it says

```
apache2-bin 2.4.54-2ubuntu1.1 -> 2.4.54-2ubuntu1.2
```

But yes this will be different for sure on Debian

**Comment by deusnovus** [comment] 2023-05-26 07:53
I also installed the latest release (VanillaOS-22.10-all.20230226.iso) and I am encountering the same issue. Software is also completely empty, only apt apps, no flatpaks / appimages etc.

**Comment by Mawfyy** [comment] 2023-06-06 13:16
I have the same problem, i restart any times and never update the packages

**Comment by me-self** [comment] 2023-10-31 23:47
Same issue here, seems related to: https://github.com/Vanilla-OS/live-iso/issues/254

**Comment by mirkobrombin** [comment] 2023-11-05 09:19
Duplicate of #254
Answer: https://github.com/Vanilla-OS/live-iso/issues/254#issuecomment-1783384842

**Closed as not planned by mirkobrombin** 2023-11-05 09:19 UTC
Labels: bug, triage
