### ISSUE TITLE
Chosen keyboard layout is ignored when entering encryption password

### ISSUE THREAD

**Issue by ghost** [Vanilla-OS/iso-builder#320] opened 2024-03-28 21:45 UTC
### Issue Description

I picked the `pl` layout during installation, but the encryption password prompt appears to be using `no`:

![image](https://github.com/Vanilla-OS/live-iso/assets/111002801/ade3288c-e72c-4c8d-8b61-46edbd76c9d4)

Nothing changed after choosing `pl` again during first setup and rebooting.

### Steps to Reproduce

- Install Orchid 120 with encryption enabled and the `pl` keyboard layout
- Reboot

### On what version of Vanilla OS this happens?

Unreleased

### Additional Information

Orchid 120.

**Comment by taukakao** [comment] 2024-03-28 23:38
Thanks for reporting.

Though this is a duplicate of https://github.com/Vanilla-OS/vanilla-installer/issues/392

**Closed as not planned by taukakao** 2024-03-28 23:38 UTC
Labels: bug, triage

**Comment by taukakao** [comment] 2024-03-28 23:41
But if you want to get this running:
"no" is just the default keyboard layout, which should be American. So try to use your keyboard as if it was american. 
When you finish the installation, you can run "abroot upgrade -f" in a terminal and it might switch to your actual layout, not sure though.
