### ISSUE TITLE
Vanilla OS for ARM devices

### ISSUE THREAD

**Issue by muhammadbahaa2001** [Vanilla-OS/iso-builder#193] opened 2023-05-31 17:34 UTC
### Feature Description

Support for ARM devices.

### Rationale

This could open the door to Apple Silicone Macs.

**Comment by kbdharun** [comment] 2023-06-01 16:33
Duplicate of https://github.com/Vanilla-OS/os/issues/87

**Closed as completed by kbdharun** 2023-06-01 16:33 UTC
Labels: triage
