### ISSUE TITLE
Parsing Error in Gnome Software During Installation (Orchid 2.0 Alpha)

### ISSUE THREAD

**Issue by RaulKong898** [Vanilla-OS/iso-builder#284] opened 2023-12-29 09:26 UTC
### Issue Description

Parse error: unexpected character '\33', expected value in Gnome Software

### Steps to Reproduce

- Open Gnome Software.
- Attempt to install certain applications or games (not specified which ones).
- Observe the error message "<data>:1:1: Parse error: unexpected character `\33', expected value" appearing as a notification.
- Note that the installation proceeds despite the error.

### On what version of Vanilla OS this happens?

Unreleased

### Additional Information

- Vanilla OS version: Orchid 2.0 (latest alpha)
- Occurrence: Intermittent, not always appearing
- Affected software: Gnome Software
- Impact: Notification appears, but installation still functions

Expected Behavior

Installation of applications and games should proceed without error messages.

Request

Please investigate and resolve this issue.

Thank you for your attention to this matter.

![Screenshot from 2023-12-29 11-17-06](https://github.com/Vanilla-OS/live-iso/assets/121046976/787bd182-2ffb-48cf-902d-8b9e28a7f834)

**Comment by mirkobrombin** [comment] 2023-12-29 09:45
Duplicate of https://github.com/Vanilla-OS/gs-plugin-vso/issues/2

**Closed as not planned by mirkobrombin** 2023-12-29 09:45 UTC
Labels: bug, triage
