### ISSUE TITLE
installer doesn't work in Orchid

### ISSUE THREAD

**Issue by SaltyRhino95857** [Vanilla-OS/iso-builder#231] opened 2023-09-01 12:11 UTC
### Issue Description

Every time you boot into live DVD/USB (tried both) the installer disappears after a couple seconds. every time you log out and back in, the same thing happens. and the icon in the main installer screen is the GNOME "icon not found" icon.

### Steps to Reproduce

- Boot into the ISO supplied in Action 8
- installer appears with glitched icon
- installer disappears
- you cant do anything until you log out, log back in, and try to enter the "Recovery" section as fast as possible and opening anything you need.

### On what version of Vanilla OS this happens?

Unreleased

**Comment by SaltyRhino95857** [comment] 2023-09-01 15:46
>     * Boot into the ISO supplied in Action [Update kinetic.yml for hindsight before node12 stuffs gets removed #8](https://github.com/Vanilla-OS/live-iso/pull/8)
pull request is wrong, i meant Action 8.

**Comment by mirkobrombin** [comment] 2023-09-01 21:11
duplicate of https://github.com/Vanilla-OS/vanilla-installer/issues/271

**Closed as not planned by mirkobrombin** 2023-09-01 21:11 UTC
Labels: bug, triage
