### ISSUE TITLE
AppImages not working (Missing FUSE)

### ISSUE THREAD

**Issue by Zukureneno** [Vanilla-OS/iso-builder#29] opened 2022-12-01 20:50 UTC
AppImages are currently not working cause they require FUSE

![image](https://user-images.githubusercontent.com/60487234/205156518-5b026bc3-1dd2-4575-b3bf-e041fbfbd8ad.png)

**Comment by Teh404Gal** [comment] 2022-12-02 07:53
Did you install the os with the app image option in the installer ticked?

**Comment by Zukureneno** [comment] 2022-12-02 09:34
> Did you install the os with the app image option in the installer ticked?

It's pre-selected. I left everything on default. So yes the AppImage option was on same as flatpak.

**Comment by mks-h** [comment] 2022-12-30 14:28
This issue should be closed now due to the stable release. If the issue is still present, it can always be reopened.

**Comment by kbdharun** [comment] 2022-12-30 14:38
> This issue should be closed now due to the stable release. If the issue is still present, it can always be reopened.

I fixed it a few weeks ago, I forgot to add `Closes #29` to my PR. OP can you close this issue.

**Closed as completed** 2022-12-30 15:36 UTC
