### ISSUE TITLE
Unable to update "System Updates"

### ISSUE THREAD

**Issue by ghost** [Vanilla-OS/iso-builder#131] opened 2023-02-09 03:48 UTC
### Issue Description

Can't update my system 

### Steps to Reproduce

- go to update the system 
- restart
- then this showed

### On what version of Vanilla OS this happens?

22.10

### Additional Information

R6

![image](https://user-images.githubusercontent.com/122128828/217713090-5b64e0d4-34a5-4857-a256-4538a17ea794.png)

**Comment by kbdharun** [comment] 2023-02-09 05:24
This is a known bug, and this announcement was made in Discord.

Hey everyone,

**We have identified a bug in ABRoot 1.4.1 that is blocking transactions**. We apologize for any inconvenience this may have caused. **A fix has been released in ABRoot 1.4.2 and is already available**.

If you have already updated to ABRoot 1.4.1 (`abroot --version`), please follow these steps to resolve the issue:

- Reboot your device
- Hold the "Shift" key to display the GRUB entries
- Choose the previous root partition
- Login and force a system upgrade using the VSO command: `sudo vso trigger-update --now`

Maybe we could make these announcements on our Twitter and Mastodon accounts too in future.

**Comment by mirkobrombin** [comment] 2023-02-09 07:01
It may also be that there has already been an update if automatic updates are turned on.
Btw alerting the user about a running or locked transaction is intended, so this is not a bug.

Closing, feel free to add more details or open a specific bug report.

**Closed as completed** 2023-02-09 07:02 UTC
Labels: bug, triage
