### ISSUE TITLE
VanillaOS updates are not triggered with the command

### ISSUE THREAD

**Issue by maxmanus96** [Vanilla-OS/iso-builder#180] opened 2023-04-14 14:40 UTC
### Issue Description

--Updates are not triggered with command provided on https://handbook.vanillaos.org/2022/12/10/updates.html

### Steps to Reproduce

-Start the terminal session
-Run `sudo vso trigger-update --now`

### On what version of Vanilla OS this happens?

22.10

### Additional Information

```maxmanus@vanilla:~$ sudo vso trigger-update --now
Triggering update now...
 WARNING  exec.start
Unlocking apt
Unlocking apt-get
Unlocking dpkg
»lokale Umleitung von /usr/sbin/grub-mkconfig zu /usr/sbin/grub-mkconfig.distrib« wird beibehalten
»lokale Umleitung von /etc/default/grub zu /etc/default/grub.distrib« wird beibehalten
Running in chroot, ignoring command 'start'
OK:1 http://ppa.launchpad.net/vanilla-os/stable/ubuntu kinetic InRelease
OK:2 http://archive.ubuntu.com/ubuntu kinetic InRelease                                                                                              
OK:3 http://archive.ubuntu.com/ubuntu kinetic-updates InRelease                                                                                      
OK:4 https://ppa.launchpadcontent.net/alessandro-strada/ppa/ubuntu kinetic InRelease                                                                 
Holen:5 http://repository.spotify.com stable InRelease [3.316 B]                                                             
OK:6 https://ppa.launchpadcontent.net/appimagelauncher-team/stable/ubuntu kinetic InRelease                                
Ign:7 https://download.docker.com/linux/ubuntu \ InRelease                              
Fehl:8 https://download.docker.com/linux/ubuntu \ Release
  404  Not Found [IP: 2600:9000:243d:8c00:3:db06:4200:93a1 443]
Fehl:5 http://repository.spotify.com stable InRelease
  Die folgenden Signaturen konnten nicht überprüft werden, weil ihr öffentlicher Schlüssel nicht verfügbar ist: NO_PUBKEY 7A3A762FAFD4A51F
Holen:9 https://apt.packages.shiftkey.dev/ubuntu any InRelease [1.228 B]
Fehl:9 https://apt.packages.shiftkey.dev/ubuntu any InRelease
  Die folgenden Signaturen konnten nicht überprüft werden, weil ihr öffentlicher Schlüssel nicht verfügbar ist: NO_PUBKEY 7FC979028B1997C1
Paketlisten werden gelesen… Fertig
E: Das Depot »https://download.docker.com/linux/ubuntu \ Release« enthält keine Release-Datei.
N: Eine Aktualisierung von solch einem Depot kann nicht auf eine sichere Art durchgeführt werden, daher ist es standardmäßig deaktiviert.
N: Weitere Details zur Erzeugung von Paketdepots sowie zu deren Benutzerkonfiguration finden Sie in der Handbuchseite apt-secure(8).
W: GPG-Fehler: http://repository.spotify.com stable InRelease: Die folgenden Signaturen konnten nicht überprüft werden, weil ihr öffentlicher Schlüssel nicht verfügbar ist: NO_PUBKEY 7A3A762FAFD4A51F
E: Das Depot »http://repository.spotify.com stable InRelease« ist nicht signiert.
N: Eine Aktualisierung von solch einem Depot kann nicht auf eine sichere Art durchgeführt werden, daher ist es standardmäßig deaktiviert.
N: Weitere Details zur Erzeugung von Paketdepots sowie zu deren Benutzerkonfiguration finden Sie in der Handbuchseite apt-secure(8).
W: GPG-Fehler: https://apt.packages.shiftkey.dev/ubuntu any InRelease: Die folgenden Signaturen konnten nicht überprüft werden, weil ihr öffentlicher Schlüssel nicht verfügbar ist: NO_PUBKEY 7FC979028B1997C1
E: Das Depot »https://apt.packages.shiftkey.dev/ubuntu any InRelease« ist nicht signiert.
N: Eine Aktualisierung von solch einem Depot kann nicht auf eine sichere Art durchgeführt werden, daher ist es standardmäßig deaktiviert.
N: Weitere Details zur Erzeugung von Paketdepots sowie zu deren Benutzerkonfiguration finden Sie in der Handbuchseite apt-secure(8).
  ERROR   exec.failed exit status 100
An error occurred while trying to update the system.
	Please try again later and report the issue if it persists.
	
	ERR_CODE: %s CMD_TR_UP_NOW
Error: exit status 1
Description: 
	Trigger a system update

Usage:
  	vso trigger-update [flags]

Flags:
	--help/-h		show this message
	--now			trigger a system update immediately

Examples:
	vso trigger-update --now

maxmanus@vanilla:~$ 
```

**Comment by mirkobrombin** [comment] 2023-04-14 18:37
There is a problem with one of your custom repositories:
```
E: Das Depot »https://download.docker.com/linux/ubuntu \ Release« enthält keine Release-Datei.
N: Eine Aktualisierung von solch einem Depot kann nicht auf eine sichere Art durchgeführt werden, daher ist es standardmäßig deaktiviert.
N: Weitere Details zur Erzeugung von Paketdepots sowie zu deren Benutzerkonfiguration finden Sie in der Handbuchseite apt-secure(8).
W: GPG-Fehler: http://repository.spotify.com stable InRelease: Die folgenden Signaturen konnten nicht überprüft werden, weil ihr öffentlicher Schlüssel nicht verfügbar ist: NO_PUBKEY 7A3A762FAFD4A51F
E: Das Depot »http://repository.spotify.com stable InRelease« ist nicht signiert.
N: Eine Aktualisierung von solch einem Depot kann nicht auf eine sichere Art durchgeführt werden, daher ist es standardmäßig deaktiviert.
N: Weitere Details zur Erzeugung von Paketdepots sowie zu deren Benutzerkonfiguration finden Sie in der Handbuchseite apt-secure(8).
W: GPG-Fehler: https://apt.packages.shiftkey.dev/ubuntu any InRelease: Die folgenden Signaturen konnten nicht überprüft werden, weil ihr öffentlicher Schlüssel nicht verfügbar ist: NO_PUBKEY 7FC979028B1997C1
E: Das Depot »https://apt.packages.shiftkey.dev/ubuntu any InRelease« ist nicht signiert.
N: Eine Aktualisierung von solch einem Depot kann nicht auf eine sichere Art durchgeführt werden, daher ist es standardmäßig deaktiviert.
N: Weitere Details zur Erzeugung von Paketdepots sowie zu deren Benutzerkonfiguration finden Sie in der Handbuchseite apt-secure(8).
  ERROR   exec.failed exit status 100
```

especially this: `E: Das Depot »https://apt.packages.shiftkey.dev/ubuntu any InRelease« ist nicht signiert.`

Please remove that repository then upgrade again.
Closing as not a bug, feel free to add more comments.

**Closed as not planned by mirkobrombin** 2023-04-14 18:37 UTC
Labels: triage
