### ISSUE TITLE
Vanilla OS 2 Install QEMU VM error

### ISSUE THREAD

**Issue by DonPedroD** [Vanilla-OS/iso-builder#252] opened 2023-10-17 15:33 UTC
### Issue Description

During installation i get a message "Something went wrong".
Looking at the log, it reports the next problem(s);
panic: interface conversion: interface {} is nil not string 

![Workspace 3_0004](https://github.com/Vanilla-OS/live-iso/assets/21311352/f39290d9-0bde-4360-bb44-f970d6c57fba)

### Steps to Reproduce

Normal installation;
RAM: 4096 MiB
Cores: 2 of 6
Virtual HD: 75 GiB

QEMU Virtual Machine Manager version 4.0.0

### On what version of Vanilla OS this happens?

Unreleased

**Comment by Gotrek77** [comment] 2023-10-21 08:03
I got the same error during installation of latest VanillaOS 2 (#82) using QEMU and Virtual Machine Manager 4.1.0 on Fedora 38.
I tried with end without disk encryption with the same results as described by DonPedroD

**Comment by mttbx** [comment] 2023-11-04 09:24
I got the same error using vmware.
Must be efi boot

**Comment by installation-scripts** [comment] 2024-01-09 10:32
Same problem on most recent iso on install. Wouldn't boot on Proxmox using standard BIOS so changed to UEFI and got the same message.

Normal installation;
RAM: 8196 MiB
Cores: 2 of 6
Any Disk Type with size: 64 GiB

Turns out the problem is the disk encryption. Turning it on during setup will make it work.

**Comment by mirkobrombin** [comment] 2024-01-30 07:27
Closing this issue as it pertains to the alpha version, and we are transitioning to the beta release. If the issue still exists or is relevant in the beta version, please feel free to reopen with updated information.

Thank you for your contribution and understanding.

--

PS. vanilla os 2 is UEFI only.

**Closed as completed by mirkobrombin** 2024-01-30 07:27 UTC
Labels: bug, triage
