### ISSUE TITLE
Firmware update failed, fixed by retagging EFI Partition

### ISSUE THREAD

**Issue by thereallinusrg** [Vanilla-OS/iso-builder#333] opened 2024-06-03 09:52 UTC
### Issue Description

The firmware update on my Thinkpad T14 Gen1 AMD failed, right after a fresh Vanilla OS Orchid install, with the following error:

`fwupd-efi version 1.6 `
`WARNING: QueryCapsuleCapabilities failed, assuming EfiResetWarm: Unsupported `
`WARNING: Could not apply capsule update: Not Found `
`WARNING: Could not apply capsules: Not Found `
`Reset System`

### Steps to Reproduce

- Have an outdated Firmware
- Click on "Download & Update" in the Software Center on the Firmware Update
- Click on Restart

### On what version of Vanilla OS this happens?

22.10

### Additional Information

After tagging the EFI Partition in Gnome Disks as "EFI System", the Firmware Update succeded.

**Comment by taukakao** [comment] 2024-06-03 09:59
Didn't think that firmware updates worked already, but good to know.

This is now a duplicate of https://github.com/Vanilla-OS/vanilla-installer/issues/380 though

But old installations will always have to set the flag manually.

**Closed as completed by taukakao** 2024-06-03 09:59 UTC
Labels: bug, triage
