### ISSUE TITLE
Windows Key/Super Key + Q Doesn't Quit Applications 

### ISSUE THREAD

**Issue by ghost** [Vanilla-OS/iso-builder#82] opened 2023-01-12 22:44 UTC
### Issue Description

This can be a bug or feature request, though I have marked it as a bug as many distros support this, so it's probably broken on my system. 

### Steps to Reproduce

- Open any application 
- Hold Windows key or super key 
- then press q 
- It should quit the application

### On what version of Vanilla OS this happens?

22.10

### Additional Information

- I am running release 3 of 22.10 Vanilla OS

**Comment by matbme** [comment] 2023-01-23 18:42
`Super + q` is not the default shortcut in GNOME for quitting applications. They use `Alt + F4`. You can change this in Settings->Keyboard->View and Customize Shortcuts->Windows->Close Window

**Comment by ghost** [comment] 2023-01-23 19:29
> `Super + q` is not the default shortcut in GNOME for quitting applications. They use `Alt + F4`. You can change this in Settings->Keyboard->View and Customize Shortcuts->Windows->Close Window

Even this doesn't work

Update: It seems like this might affect Lenovo laptops as `F4` is called `AudioMicMute`
![image](https://user-images.githubusercontent.com/122128828/214132211-a24d8028-497d-4d1d-8625-51776a14d331.png)

**Comment by matbme** [comment] 2023-01-23 19:32
Maybe it's related to your keyboard layout? I have this exact binding and it works fine on my computer

**Comment by ghost** [comment] 2023-01-23 19:34
> Maybe it's related to your keyboard layout? I have this exact binding and it works fine on my computer

Yea on Lenovo laptops it's actually called AudioMicMute, but when you run windows if you press esc it changes the layout to F1-F12 regular functions

**Comment by matbme** [comment] 2023-01-23 19:44
You can use "dconf Editor" to check whether `close` is bound correctly. It should be like this:

![image](https://user-images.githubusercontent.com/48367298/214134528-ea03cc28-3fe2-45f4-b8f4-e29b8ddabb82.png)

**Comment by Muqtxdir** [comment] 2023-01-29 15:10
this seems like a quirk because of your different hw, so this isnt problem caused by vanilla

**Comment by mirkobrombin** [comment] 2023-01-29 15:43
> this seems like a quirk because of your different hw, so this isnt problem caused by vanilla

Closing since not a bug in our end. Feel free to keep the discussion up.

**Closed as completed by mirkobrombin** 2023-01-29 15:43 UTC
Labels: bug, triage
