### ISSUE TITLE
ISO missing partition table (build 94)

### ISSUE THREAD

**Issue by ghost** [Vanilla-OS/iso-builder#280] opened 2023-12-21 01:56 UTC
### Issue Description

If you download alpha build 94 of v2 and attempt to burn the ISO to USB, you are warned that it is missing the bootable partition table.

![Snapshot_2023-12-20_20-53-00](https://github.com/Vanilla-OS/live-iso/assets/61557098/125609c8-3776-46de-b78a-991ce01fc775)

### Steps to Reproduce

* Download build 94
* Select the file to burn to USB (I used Balena Etcher)

### On what version of Vanilla OS this happens?

Unreleased

**Comment by ghost** [comment] 2023-12-21 02:12
I confirmed in the previous build 93

**Comment by taukakao** [comment] 2023-12-21 08:00
duplicate of #244

**Closed as completed by taukakao** 2023-12-21 08:00 UTC
Labels: bug, duplicate, triage
